import { Model, DataTypes } from "sequelize";
import { sequelize } from "../../utils/database";

export class ShiftLogModel extends Model {}

ShiftLogModel.init(
    {
        id: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement: true,
        },
        date: { type: DataTypes.STRING, allowNull: true },
        shift: { type: DataTypes.STRING, allowNull: true },
        otHours: { type: DataTypes.FLOAT, allowNull: true },
        inTime: { type: DataTypes.DATE, allowNull: true },
        outTime: { type: DataTypes.DATE, allowNull: true },
        workingHours: { type: DataTypes.FLOAT, allowNull: true },
        monthYear: { type: DataTypes.STRING, allowNull: true },
        vehicleModel: { type: DataTypes.STRING, allowNull: true },
        regNo: { type: DataTypes.STRING, allowNull: true },
        chassisNo: { type: DataTypes.STRING, allowNull: true },
        gvw: { type: DataTypes.FLOAT, allowNull: true },
        payload: { type: DataTypes.FLOAT, allowNull: true },
        startingKm: { type: DataTypes.FLOAT, allowNull: true },
        endingKm: { type: DataTypes.FLOAT, allowNull: true },
        totalKm: { type: DataTypes.FLOAT, allowNull: true },
        fuelAvg: { type: DataTypes.FLOAT, allowNull: true },
        previousKmpl: { type: DataTypes.FLOAT, allowNull: true },
        clusterKmpl: { type: DataTypes.FLOAT, allowNull: true },
        highwaySweetSpotPercent: { type: DataTypes.FLOAT, allowNull: true },
        normalRoadSweetSpotPercent: { type: DataTypes.FLOAT, allowNull: true },
        hillsRoadSweetSpotPercent: { type: DataTypes.FLOAT, allowNull: true },
        purposeOfTrial: { type: DataTypes.STRING, allowNull: true },
        reason: { type: DataTypes.STRING, allowNull: true },
        dateOfSale: { type: DataTypes.STRING, allowNull: true },
        trailId: { type: DataTypes.STRING, allowNull: true },
        fromPlace: { type: DataTypes.STRING, allowNull: true },
        toPlace: { type: DataTypes.STRING, allowNull: true },
        presentLocation: { type: DataTypes.STRING, allowNull: true },
        employeeName: { type: DataTypes.STRING, allowNull: true },
        vecvReportingPerson: { type: DataTypes.STRING, allowNull: true },
        employeePhoneNo: { type: DataTypes.STRING, allowNull: true },
        employeeCode: { type: DataTypes.STRING, allowNull: true },
        dicvInchargeName: { type: DataTypes.STRING, allowNull: true },
        dicvInchargePhoneNo: { type: DataTypes.STRING, allowNull: true },
        dealerName: { type: DataTypes.STRING, allowNull: true },
        capitalizedVehicleOrCustomerVehicle: { type: DataTypes.STRING, allowNull: true },
        customerVehicle: { type: DataTypes.STRING, allowNull: true },
        capitalizedVehicle: { type: DataTypes.STRING, allowNull: true },
        coDriverName: { type: DataTypes.STRING, allowNull: true },
        coDriverPhoneNo: { type: DataTypes.STRING, allowNull: true },
        driverStatus: { type: DataTypes.STRING, allowNull: true },
        customerName: { type: DataTypes.STRING, allowNull: true },
        customerDriverName: { type: DataTypes.STRING, allowNull: true },
        customerDriverNo: { type: DataTypes.STRING, allowNull: true },
        vehicleNo: { type: DataTypes.STRING, allowNull: true },
        imageVideoUrls: { type: DataTypes.JSON, allowNull: true },
        inchargeSign: { type: DataTypes.STRING, allowNull: true },
        trialKMPL: { type: DataTypes.STRING, allowNull: true },
        vehicleOdometerStartingReading: { type: DataTypes.STRING, allowNull: true },
        vehicleOdometerEndingReading: { type: DataTypes.STRING, allowNull: true },
        trialKMS: { type: DataTypes.STRING, allowNull: true },
        trialAllocation: { type: DataTypes.STRING, allowNull: true },
        region: { type: DataTypes.STRING, allowNull: true },
        allocation: { type: DataTypes.STRING, allowNull: true },
    },
    {
        sequelize,
        tableName: "shift_logs",
        timestamps: true,
    }
);
